export default {
  // API 接口请求优先，数据格式保持和 data 一致
  api: '',
  // api 为空则使用 data 静态数据
  data: [
    {
      id: 'info-037',
      title: '腾讯研究院AI速递 20251110 - AI六巨头激辩AGI路径',
      date: '2025-11-10',
      categories: 'AI技术',
      tags: ['Grok 4', 'GPT-5', 'Google Nano Banana', 'AI模型', '李飞飞', '黄仁勋'],
      cover: 'https://wp-cdn.4ce.cn/v2/TiryGCQ.jpeg',
      content: '今日AI领域重大进展频频出现，Grok 4深夜升级至200万token上下文窗口，GPT-5-Codex Mini发布性能提升50%，谷歌Nano Banana 2预览版现身支持原生2K超分，Utopai与国际资本加码AI影视，Google Finance重磅升级整合深度搜索，诺贝尔奖得主团队RFdiffusion快速生成抗体，中国登月火箭验证飞行，AI六巨头激辩AGI路径，Kimi K2位列全球第二，HuggingFace推出200页LLM训练指南。',
      recommend: true,
      top: true,
      link: '/article/daily-ai-news-november-10-2025'
    },
    {
      id: 'info-036',
      title: '每日AI新闻速递-11月6日：谷歌Project Suncatcher卫星AI计划，Anthropic Agent效率革命，UniWorld V2图像编辑突破',
      date: '2025-11-06',
      categories: 'AI技术',
      tags: ['AI新闻', '谷歌', '太空AI', 'Anthropic', '图像编辑', 'QQ浏览器', 'Earth AI', '小鹏', '人形机器人', '具身智能', 'ElevenLabs'],
      cover: 'https://wp-cdn.4ce.cn/v2/D7dVLpf.jpeg',
      content: '今日AI领域重磅更新：谷歌宣布Project Suncatcher计划将TPU送上太空，Anthropic推出代码执行新范式让Token消耗暴降98.7%，兔展智能&北大发布UniWorld-V2图像编辑模型，QQ浏览器推出AI+小窗集成14种AI工具，谷歌重磅升级Earth AI发布三大基础模型，小鹏展示全新IRON人形机器人，Generalist推出具身基础模型GEN-0。',
      recommend: true,
      top: true,
      link: '/article/daily-ai-news-november-06-2025'
    },
    {
      id: 'info-035',
      title: '每日AI新闻速递-10月20日：英伟达亮相首片美国造Blackwell芯片，李飞飞新世界模型单卡实时渲染，Manus 1.5全包上线测试',
      date: '2025-10-20',
      categories: 'AI技术',
      tags: ['AI新闻', '英伟达', 'Blackwell', '台积电', '李飞飞', 'World Labs', 'RTFM', '世界模型', 'Anthropic', 'Agent Skills', 'Manus', 'Windows 11', 'Copilot', '百度', 'PaddleOCR', 'DeepMind', '核聚变', '哈佛', 'Reddit', 'Karpathy', 'AGI'],
      cover: 'https://wp-cdn.4ce.cn/v2/Akq25sk.png',
      content: '今日AI领域重磅更新：英伟达与台积电在亚利桑那工厂历史性亮相首片美国造Blackwell芯片晶圆，李飞飞World Labs发布RTFM实时生成式世界模型单块H100即可实时渲染3D世界，Anthropic推出Agent Skills可按需加载提示词代码包，Manus 1.5引入内建浏览器让AI自主测试修Bug，Windows 11大更新集成Copilot Vision和Manus强势上岗，百度开源PaddleOCR-VL登顶全球第一。',
      recommend: true,
      top: true,
      link: '/article/daily-ai-news-october-20-2025'
    },
    {
      id: 'info-034',
      title: '每日AI新闻速递-10月18日：谷歌Veo 3.1对标Sora 2用户狂刷2.75亿条，Claude Haiku 4.5成本降三分之一性能超Sonnet 4',
      date: '2025-10-18',
      categories: 'AI技术',
      tags: ['AI新闻', '谷歌', 'Veo 3.1', 'Sora 2', '视频生成', 'Anthropic', 'Claude Haiku 4.5', '阿里', '千问', 'Memory', '字节', '豆包', '语音合成', '抗癌AI', 'LangChain', '上下文工程', '黄仁勋', 'NVIDIA', '红杉'],
      cover: 'https://wp-cdn.4ce.cn/v2/f0U3ZDC.png',
      content: '今日AI领域重磅更新：谷歌发布视频生成模型Veo 3.1支持720p/1080p分辨率最长148秒视频用户已生成2.75亿条，Anthropic推出轻量级Claude Haiku 4.5成本仅为Sonnet 4三分之一编码性能相媲美，阿里千问上线Memory功能让AI拥有跨对话记忆能力，字节豆包语音合成2.0实现情境理解与语气把控。',
      recommend: true,
      top: false,
      link: '/article/daily-ai-news-october-18-2025'
    },
    {
      id: 'info-033',
      title: '从无图到轻图，大模型时代智驾地图新角逐，腾讯地图市场份额登顶49%',
      date: '2025-10-17',
      categories: '智能驾驶',
      tags: ['智驾地图', '腾讯地图', 'HD Air', '轻地图', '高德', '百度', '城市NOA', '辅助驾驶', '大模型', '端到端', '智能网联汽车', '地图技术', '市场格局', '云图'],
      cover: 'https://wp-cdn.4ce.cn/v2/JT4b2Dn.png',
      content: '智驾地图技术经历从高精地图到无图再到轻图的三阶段演变，腾讯地图凭借HD Air轻量级高精数据产品在城市NOA市场占据49.01%份额登顶，高德紧随其后占47.9%，AI大模型技术推动地图形态向模型化演进，智驾地图市场2025年预计达54亿元2030年有望达117亿元。',
      recommend: true,
      top: false,
      link: '/article/daily-ai-news-october-17-2025'
    },
    {
      id: 'info-032',
      title: '每日AI新闻速递-10月16日：万里眼90GHz示波器打破封锁，苹果M5芯片AI性能飙升3.5倍，Gemini 3.0复刻操作系统',
      date: '2025-10-16',
      categories: 'AI技术',
      tags: ['AI新闻', '万里眼', '示波器', '苹果', 'M5芯片', 'Gemini 3.0', '操作系统', '阿里', 'Qwen3-VL', '科大讯飞', '同传大模型', 'OPPO', 'ColorOS 16', 'NewtonBench', 'Anthropic', 'Ilya', 'AGI', '诺贝尔经济学奖'],
      cover: 'https://wp-cdn.4ce.cn/v2/aAjjG0L.png',
      content: '今日AI领域重磅更新：万里眼发布90GHz超高速实时示波器打破西方技术封锁，苹果M5芯片AI性能提升3.5倍10月17日开启预购，谷歌Gemini 3.0 Pro单HTML文件复刻macOS等操作系统，阿里开源Qwen3-VL 4B与8B版本超越同级模型，科大讯飞同传大模型升级AI翻译耳机发布。',
      recommend: true,
      top: true,
      link: '/article/daily-ai-news-october-16-2025'
    },
    {
      id: 'info-031',
      title: '每日AI新闻速递-10月15日：英伟达3999美元AI超算发布，Karpathy开源nanochat项目，微软首款自研文生图模型登场',
      date: '2025-10-15',
      categories: 'AI技术',
      tags: ['AI新闻', '英伟达', 'DGX Spark', 'AI超算', 'Karpathy', 'nanochat', 'ChatGPT', '微软', 'MAI-Image-1', '文生图', '腾讯优图', 'Youtu-Embedding', 'QQ浏览器', '较真AI', 'SpaceX', '星舰', 'Cathie Wood', 'n8n'],
      cover: 'https://wp-cdn.4ce.cn/v2/k0iwz0c.png',
      content: '今日AI领域重磅更新：英伟达发布3999美元DGX Spark个人AI超算可运行2000亿参数模型，Karpathy开源nanochat项目100美元手搓ChatGPT，微软推出首款自研文生图模型MAI-Image-1登榜第9名，腾讯优图开源Youtu-Embedding文本表示模型，研究发现对AI粗鲁语气正确率更高。',
      recommend: true,
      top: true,
      link: '/article/daily-ai-news-october-15-2025'
    },
    {
      id: 'info-030',
      title: '每日AI新闻速递-10月14日：OpenAI自研芯片与博通合作，Gemini 3.0前端开发能力惊艳，Mamba-3架构创新突破',
      date: '2025-10-14',
      categories: 'AI技术',
      tags: ['AI新闻', 'OpenAI', '博通', '芯片', 'Gemini 3.0', '前端开发', 'Mamba-3', 'SAM 3', '概念分割', '苹果', 'AI眼镜', 'visionOS', 'LiblibAI', 'ReasoningBank', '宇树机器人', 'Sam Altman'],
      cover: 'https://wp-cdn.4ce.cn/v2/k0iwz0c.png',
      content: '今日AI领域重磅更新：OpenAI官宣与博通100亿瓦定制芯片合作推动博通股价飙涨10%，谷歌Gemini 3.0预告展现强大前端开发能力可一键生成网页游戏，Mamba-3进入ICLR 2026采用三大创新设计，SAM 3实现概念分割性能提升2倍，苹果AI眼镜曝光搭载visionOS系统。',
      recommend: true,
      top: true,
      link: '/article/daily-ai-news-october-14-2025'
    },
    {
      id: 'info-029',
      title: '每日AI新闻速递-9月30日：DeepSeek-V3.2发布并大幅降价，智源开源RoboBrain-X0通用机器人基座，量子计算突破6100比特',
      date: '2025-09-30',
      categories: 'AI技术',
      tags: ['AI新闻', 'DeepSeek', '稀疏注意力', 'API降价', '智源', 'RoboBrain-X0', '机器人基座', '腾讯', '混元3D', 'GPT-5', '量子计算', 'AlphaGo', 'Flash Attention', '英伟达', '量子比特'],
      cover: 'https://wp-cdn.4ce.cn/v2/hK93DGf.png',
      content: '今日AI领域重磅更新：DeepSeek发布V3.2-Exp版本引入稀疏注意力机制API降价50%，智源开源RoboBrain-X0实现零样本跨本体泛化，腾讯混元3D-Omni推出业界首个统一多控制3D生成模型，GPT-5半小时解决量子NP难题，加州理工创造6100比特量子计算新纪录。',
      recommend: true,
      top: true,
      link: '/article/daily-ai-news-september-30-2025'
    },
    {
      id: 'info-028',
      title: '每日AI新闻速递-9月29日：OpenAI爆出GPT门事件，腾讯混元图像3.0开源发布，快手KAT系列编程大模型突破',
      date: '2025-09-29',
      categories: 'AI技术',
      tags: ['AI新闻', 'OpenAI', 'GPT门', '腾讯', '混元图像', '快手', 'KAT', '编程大模型', '学而思', 'AI教师', 'Meta', '人形机器人', '强化学习', 'DeepMind', 'Veo 3', '黄仁勋'],
      cover: 'https://wp-cdn.4ce.cn/v2/hK93DGf.png',
      content: '今日AI领域重磅更新：OpenAI被曝偷换模型引发GPT门争议，腾讯发布80B参数混元图像3.0开源生图模型，快手推出KAT系列编程大模型在SWE-Bench达73.4%解决率，学而思提出AI教师分级理论，Meta投资数十亿研发人形机器人，强化学习之父批评大语言模型。',
      recommend: true,
      top: true,
      link: '/article/daily-ai-news-september-29-2025'
    },
    {
      id: 'info-027',
      title: '每日AI新闻速递-9月28日：ChatGPT推出主动推送功能Pulse，谷歌发布机器人专用Gemini模型，腾讯混元3D开源组件生成技术',
      date: '2025-09-28',
      categories: 'AI技术',
      tags: ['AI新闻', 'ChatGPT', 'Pulse', 'OpenAI', '谷歌', 'Gemini Robotics', '腾讯', '混元3D', 'Kimi', 'Agent', '红杉', 'AI生产力', '机器人', '3D生成'],
      cover: 'https://wp-cdn.4ce.cn/v2/hG7qsDQ.png',
      content: '今日AI领域重磅更新：OpenAI推出ChatGPT主动推送功能Pulse向Pro用户开放，谷歌DeepMind发布Gemini Robotics 1.5让机器人学会思考，腾讯混元3D开源业界首个原生3D组件生成模型，Kimi发布全新Agent模型OK Computer，红杉报告揭示AI生产力悖论。',
      recommend: true,
      top: true,
      link: '/article/daily-ai-news-september-28-2025'
    },
    {
      id: 'info-001',
      title: '380亿重庆汽车黑马，收编吉利2500人军团 - 千里智驾崛起',
      date: '2025-08-05',
      categories: '行业事件',
      tags: ['智能驾驶', '汽车科技', '吉利'],
      cover: 'https://wp-cdn.4ce.cn/v2/DLm6mwS.png',
      content: '深度分析千里科技如何通过收编吉利2500人军团，打造智能驾驶新格局。印奇掌舵的千里科技正在构建一个全新的"AI+车"生态体系。',
      recommend: true,
      top: false,
      link: '/article/380亿重庆汽车黑马收编吉利2500人军团-千里智驾崛起'
    },
    {
      id: 'info-002',
      title: 'Google 发布的 Genie 3 能从文字或图片即时生成可玩的 3D 互动世界',
      date: '2025-08-07',
      categories: 'AI技术',
      tags: ['Google', 'Genie 3', '3D生成', 'AI', '世界模型', 'DeepMind'],
      cover: 'https://wp-cdn.4ce.cn/v2/bpOe0kA.jpeg',
      content: 'Google发布的Genie 3能从文字或图片即时生成可玩的3D互动世界，支持实时交互、720p画质、24fps帧率，在清晰度、时长、连贯性与可编辑性上都大幅提升。',
      recommend: true,
      top: true,
      link: '/article/Google发布的Genie3能从文字或图片即时生成可玩的3D互动世界'
    },
    {
      id: 'info-003',
      title: 'OpenAI终于"open"了一下 - 发布两款开源大语言模型',
      date: '2025-08-07',
      categories: 'AI技术',
      tags: ['OpenAI', '开源模型', 'GPT', 'gpt-oss-120b', 'gpt-oss-20b', 'AI'],
      cover: 'https://wp-cdn.4ce.cn/v2/4SOuhj7.jpeg',
      content: 'OpenAI发布两款开源大语言模型：gpt-oss-120b和gpt-oss-20b，分别针对高性能和轻量化场景优化，在编程竞赛平台Codeforces上表现优异。',
      recommend: true,
      top: false,
      link: '/article/OpenAI终于open了一下-发布两款开源大语言模型'
    }
    ,
    {
      id: 'info-004',
      title: '2025世界机器人大会（北京）',
      date: '2025-08-11',
      categories: '行业事件',
      tags: ['机器人', '具身智能', '产业趋势', '人形机器人'],
      cover: 'https://wp-cdn.4ce.cn/v2/YZ8LorG.png',
      content: '2025年世界机器人大会在北京亦创国际会展中心举办，主题“让机器人更智慧，让具身更智能”。200+企业、1500+展品、百余新品首发，论坛聚焦产业发展、创新应用与技术融合。',
      recommend: true,
      top: true,
      link: '/info-dynamic/wrc-2025-beijing'
    },
    {
      id: 'info-005',
      title: '谷歌nano banana正式上线：单图成本不到3毛钱，比OpenAI便宜95%',
      date: '2025-01-27',
      categories: 'AI技术',
      tags: ['谷歌', 'AI图像生成', 'Gemini', 'nano-banana', '图像编辑', '成本优势'],
      cover: 'https://wp-cdn.4ce.cn/v2/4SOuhj7.jpeg',
      content: '谷歌神秘的图像生成与编辑模型nano banana终于正式上线，正式命名为gemini-2.5-flash-image-preview，具有SOTA的图像生成能力、惊人的角色一致性和闪电般的速度。',
      recommend: true,
      top: true,
      link: '/article/谷歌nano-banana正式上线-单图成本不到3毛钱-比OpenAI便宜95'
    },
    {
      id: 'info-006',
      title: 'AI周报：2025年9月第二周行业动态汇总',
      date: '2025-09-08',
      categories: 'AI技术',
      tags: ['AI周报', '人工智能', '期权激励', 'OpenAI', '人形机器人', '行业动态'],
      cover: 'https://wp-cdn.4ce.cn/v2/4SOuhj7.jpeg',
      content: '本周AI行业重大动态：大厂掀起期权激励潮，OpenAI预计年烧80亿美元，AI岗位薪资持续攀升，人形机器人订单创新高。深度解读行业变化趋势和投资机会。',
      recommend: true,
      top: true,
      link: '/article/ai-weekly-report-2025-september-week2'
    },
    {
      id: 'info-007',
      title: '华为昇腾重大战略转型：从ASIC架构转向CUDA生态兼容',
      date: '2025-09-10',
      categories: 'AI芯片',
      tags: ['华为', '昇腾', 'CUDA', 'ASIC', 'GPGPU', 'AI芯片', '生态转型'],
      cover: 'https://wp-cdn.4ce.cn/v2/4SOuhj7.jpeg',
      content: '华为昇腾AI芯片正在进行重大战略调整，从专用ASIC架构转向通用GPGPU设计，并通过软件兼容层拥抱CUDA生态。这一转型将如何影响国产AI芯片格局？深度分析战略背景、技术路径和市场影响。',
      recommend: true,
      top: true,
      link: '/article/huawei-ascend-cuda-strategy'
    },
    {
      id: 'info-008',
      title: '黑芝麻智能亏损7.6亿：智驾芯片第一股的增长困境',
      date: '2025-09-10',
      categories: 'AI芯片',
      tags: ['黑芝麻智能', '智驾芯片', '汽车科技', '财务分析', '国产芯片', '自动驾驶'],
      cover: 'https://wp-cdn.4ce.cn/v2/4SOuhj7.jpeg',
      content: '国产智驾芯片龙头黑芝麻智能2025年上半年财报显示，营收增长放缓至40.4%，毛利率腰斩至24.8%，亏损高达7.6亿元。深度分析这家曾经明星企业面临的挑战与困境。',
      recommend: true,
      top: false,
      link: '/article/heisesame-financial-crisis-analysis'
    },
    {
      id: 'info-009',
      title: '2025年中国智驾领域技术领袖盘点：13位一号位的技术征程',
      date: '2025-09-11',
      categories: '产业洞察',
      tags: ['自动驾驶', '技术领袖', '智能驾驶', '端到端', 'VLA', '世界模型', '人工智能', '汽车科技'],
      cover: 'https://wp-cdn.4ce.cn/v2/opMSXT2.png',
      content: '深度盘点2025年中国自动驾驶领域的13位技术领袖，从理想郎咸朋到小马智行楼天城，他们如何引领端到端、VLA和世界模型技术革命，书写中国智驾的未来。',
      recommend: true,
      top: false,
      link: '/article/china-autonomous-driving-leaders-2025'
    },
    {
      id: 'info-010',
      title: '慕尼黑车展：中国智驾供应链的全球化突围战',
      date: '2025-09-11',
      categories: '行业事件',
      tags: ['慕尼黑车展', '智能驾驶', '供应链', '出海', '地平线', 'Momenta', '知行科技', '汽车科技'],
      cover: 'https://wp-cdn.4ce.cn/v2/MSUBOF8.png',
      content: '2025年慕尼黑车展见证了中国智能驾驶供应链企业的集体崛起，中国参展企业数量增长40%，从地平线到Momenta，中国企业通过技术输出和本地化布局重塑全球汽车产业格局。',
      recommend: true,
      top: false,
      link: '/article/munich-auto-show-2025-chinese-supply-chain'
    },
    {
      id: 'info-011',
      title: '每日AI新闻速递-9月11日',
      date: '2025-09-11',
      categories: 'AI技术',
      tags: ['AI新闻', '英伟达', 'Claude', '腾讯', '快手', '谷歌', 'AI编程', '生成式AI', 'AI芯片'],
      cover: 'https://wp-cdn.4ce.cn/v2/bT8vK9L.png',
      content: '今日AI行业重磅动态：英伟达Rubin CPX GPU支持百万Token推理，Claude支持直接生成Office文件，腾讯CodeBuddy开启AI编程L4时代，快手AIGC超级员工一句话生成短视频，AI技术全面进入实用化新阶段。',
      recommend: true,
      top: false,
      link: '/article/daily-ai-news-september-11-2025'
    },
    {
      id: 'info-012',
      title: '今日AI新闻速递-2025年9月12日',
      date: '2025-09-12',
      categories: 'AI技术',
      tags: ['AI新闻', 'ChatGPT', 'Thinking Machines', '微信', '腾讯', '强化学习', '生成式AI', '技术速递'],
      cover: '/assets/images/banner/ai-news-banner.webp',
      content: '汇总今日重要AI新闻动态：估值120亿美元的Thinking Machines发布首篇研究博客、ChatGPT正式支持MCP协议、微信智能回复功能上线、NVIDIA发布3D模型生成AI Blueprint等九大重要资讯。',
      recommend: true,
      top: true,
      link: '/article/daily-ai-news-september-12-2025'
    },
    {
      id: 'info-013',
      title: '自动驾驶VLA再升级！博世IRL-VLA：打造全新闭环强化学习框架',
      date: '2025-09-12',
      categories: '技术分析',
      tags: ['自动驾驶', 'VLA', '强化学习', '博世', '清华', '视觉语言模型', '端到端', '世界模型'],
      cover: '/assets/images/day.jpeg',
      content: '深度解析博世与清华团队联合推出的IRL-VLA框架，通过逆向强化学习奖励世界模型实现自动驾驶VLA的闭环训练突破。在CVPR2025自动驾驶大奖赛中获得亚军，NAVSIM v2基准测试达到SOTA性能。',
      recommend: true,
      top: false,
      link: '/article/autonomous-driving-vlm-analysis'
    },
    {
      id: 'info-014',
      title: 'AI周报：2025年9月第三周行业动态汇总',
      date: '2025-09-15',
      categories: 'AI技术',
      tags: ['AI周报', '人事变动', '腾讯', 'OpenAI', 'xAI', '马斯克', '支付宝', 'AI付', '数据标注', '科创委员会'],
      cover: '/assets/images/banner/ai-weekly-banner.webp',
      content: '本周AI行业重磅动态汇总：腾讯辟谣姚顺雨上亿薪资传闻，宇树王兴兴、智元彭志辉获科创咨询委员新身份，xAI裁撤500名数据标注员，支付宝推出首个"AI付"服务，多项技术突破引领行业变革。',
      recommend: true,
      top: false,
      link: '/article/ai-weekly-report-2025-september-week3'
    },
    {
      id: 'info-015',
      title: '每日AI新闻速递-9月15日：OpenAI重组在即，AI创意产业全面爆发',
      date: '2025-09-15',
      categories: 'AI技术',
      tags: ['AI新闻', 'OpenAI', '微软', '重组', 'AI电影', '音乐生成', '美团', 'Agent', '语音合成', '数学AI'],
      cover: '/assets/images/day.jpeg',
      content: '今日AI行业重磅动态：OpenAI与微软发布重组备忘录估值超1000亿美元，前谷歌X团队AI电影锁定戛纳，MiniMax Music 1.5支持4分钟音乐创作，美团AI Agent"小美"公测上线，B站开源精准口型语音合成模型，AI数学取得历史性突破。',
      recommend: true,
      top: true,
      link: '/article/daily-ai-news-september-15-2025'
    },
    {
      id: 'info-016',
      title: '蔚来生死线拐点：70亿融资背后的盈利冲刺战',
      date: '2025-09-15',
      categories: '汽车科技',
      tags: ['蔚来', '融资', '新能源汽车', '财务分析', '李斌', '盈利', '资产负债率', '新势力'],
      cover: 'https://wp-cdn.4ce.cn/v2/vFEbizI.jpeg',
      content: '蔚来汽车再次成功融资超70亿元，在资产负债率高达93.4%的紧张状态下，这笔资金将如何助力蔚来冲击年底盈利目标？深度解析蔚来11年融资历程、当前财务状况与未来挑战。',
      recommend: true,
      top: false,
      link: '/article/nio-financing-september-2025'
    },
    {
      id: 'info-017',
      title: '智能网联汽车周刊：市值普涨与行业规范并行，技术创新加速落地',
      date: '2025-09-15',
      categories: '汽车科技',
      tags: ['智能网联汽车', '车企市值', '网络整治', 'Robotaxi', '自动驾驶', '哈啰出行', '中汽中心', '禾赛科技'],
      cover: 'https://wp-cdn.4ce.cn/v2/vFEbizI.jpeg',
      content: '本周智能网联汽车行业重磅动态：8月全球车企市值超七成增长，工信部启动网络乱象专项整治，中汽中心20亿建设智能网联科技创新基地，哈啰发布首款自研Robotaxi，Uber与Momenta将在慕尼黑启动无人驾驶服务。',
      recommend: true,
      top: false,
      link: '/article/smart-connected-car-weekly-september-2025'
    },
    {
      id: 'info-018',
      title: '王飞跃三问AI：人类还有希望吗？',
      date: '2025-09-16',
      categories: 'AI技术',
      tags: ['AI', '人工智能', '王飞跃', '大模型', '人形机器人', '未来趋势'],
      cover: '/assets/images/banner/ai-future-banner.webp',
      content: '中科院自动化所王飞跃研究员在PEC 2025 AI创新者大会上提出AI三大核心问题，描绘由"三个世界三种人类"组成的未来社会蓝图，预测信任力和注意力将成为新商品，人工智能将创造更多更好的工作。',
      recommend: true,
      top: false,
      link: '/article/wang-feiyu-three-questions-ai-september-2025'
    },
    {
      id: 'info-019',
      title: '每日AI新闻速递-9月16日：Google Gemini登顶App Store，xAI速度突破，AI部长上岗',
      date: '2025-09-16',
      categories: 'AI技术',
      tags: ['AI新闻', 'Google', 'Gemini', 'xAI', 'Grok', '可灵', '数字人', '腾讯', '混元', 'AI部长', '程序员'],
      cover: '/assets/images/day.jpeg',
      content: '今日AI行业重磅动态：Google Gemini凭Nano Banana功能超越ChatGPT登顶App Store，xAI发布75 token/秒超快模型，阿尔巴尼亚任命全球首个AI部长，腾讯混元AI绘画技术实现3倍提升，AI应用市场竞争进入白热化阶段。',
      recommend: true,
      top: false,
      link: '/article/daily-ai-news-september-16-2025'
    },
    {
      id: 'info-020',
      title: 'AI记忆进化论：从被动存储到智能管理',
      date: '2025-09-16',
      categories: '技术分析',
      tags: ['AI', '记忆系统', 'RAG', 'Agent', '开源', 'Mem0', 'Zep', 'Letta', '技术趋势'],
      cover: '/assets/images/banner/ai-memory-banner.webp',
      content: '深度解析AI记忆系统的技术演进路线，从传统RAG到智能化记忆管理，探讨记忆系统如何成为AI竞争的下一个战场。涵盖Mem0、Zep、Letta等主流开源项目，以及MemU、MIRIX、MemOS等新兴技术方案。',
      recommend: true,
      top: false,
      link: '/article/ai-memory-evolution-september-2025'
    },
    {
      id: 'info-021',
      title: '智驾端到端落地真相：从特斯拉到华为的技术革命与量产竞赛',
      date: '2025-09-22',
      categories: '技术分析',
      tags: ['自动驾驶', '端到端', '特斯拉', '华为', '小鹏', 'Waymo', '智能驾驶', 'AI技术', '大模型'],
      cover: 'https://wp-cdn.4ce.cn/v2/RfExAjT.png',
      content: '深度解析端到端自动驾驶技术的演进历程，对比特斯拉、Waymo、华为、小鹏等头部玩家的技术路线与商业化时间线。从ALVINN到大模型时代，探讨这场AI驾驶革命的现实进展与未来趋势。',
      recommend: true,
      top: false,
      link: '/article/end-to-end-autonomous-driving-september-2025'
    },
    {
      id: 'info-022',
      title: '每日AI新闻速递-9月22日：Chrome AI大更新，Notion 3.0进入Agent时代，腾讯混元3D革命',
      date: '2025-09-22',
      categories: 'AI技术',
      tags: ['AI新闻', 'Chrome', 'Gemini', 'Notion', 'Agent', '腾讯', '混元3D', '阿里', 'Luma AI', '生成式AI', '生物技术'],
      cover: '/assets/images/day.jpeg',
      content: '今日AI行业重磅动态：Chrome自2008年来最大更新集成Gemini AI，Notion 3.0引入Agent功能实现自主工作，腾讯发布混元3D Studio整合全流程，阿里开源动作生成模型，奥特曼押注逆龄大脑药物，AI原生应用时代全面到来。',
      recommend: true,
      top: false,
      link: '/article/daily-ai-news-september-22-2025'
    },
    {
      id: 'info-023',
      title: '每日AI新闻速递-9月23日：联发科天玑9500芯片发布，谷歌革新Agent思考范式，OpenAI算力投入创新高',
      date: '2025-09-23',
      categories: 'AI技术',
      tags: ['AI新闻', '联发科', '天玑9500', '谷歌', 'Deep Research', 'OpenAI', '算力', '可灵AI', '美团', '百度', 'DeepSeek', '芯片', 'Agent'],
      cover: '/assets/images/banner/ai-news-banner.webp',
      content: '今日AI行业重磅动态：联发科发布天玑9500旗舰AI芯片，NPU性能提升111%；谷歌开源Deep Research框架突破传统Agent模式；OpenAI计划投入3500亿美元算力；可灵AI 2.5视频模型实现动作戏突破；美团、百度、DeepSeek模型技术全面升级。',
      recommend: true,
      top: false,
      link: '/article/daily-ai-news-september-23-2025'
    },
    {
      id: 'info-024',
      title: '每日AI新闻速递-9月24日：英伟达千亿投资OpenAI，阿里开源全模态大模型，具身智能迎来重大突破',
      date: '2025-09-24',
      categories: 'AI技术',
      tags: ['AI新闻', '英伟达', 'OpenAI', '阿里', 'Qwen3-Omni', '智元机器人', 'GO-1', '具身智能', 'MiniCPM-V', '清华', '无问芯穹', 'Kimi', 'Agent'],
      cover: '/assets/images/day.jpeg',
      content: '今日AI行业重磅动态：英伟达官宣向OpenAI投资1000亿美元打造AI巨兽，阿里开源原生多模态模型Qwen3-Omni对标闭源强模型，智元机器人GO-1通用具身基座大模型全面开源，清华MiniCPM-V 4.5以8B参数硬刚72B大模型，AI基础设施进入Agent时代。',
      recommend: true,
      top: false,
      link: '/article/daily-ai-news-september-24-2025'
    },
    {
      id: 'info-025',
      title: '每日AI新闻速递-9月25日：谷歌Mixboard重新定义AI画板，通义万相2.5音画同步突破，可灵2.5成本暴降30%',
      date: '2025-09-25',
      categories: 'AI技术',
      tags: ['AI新闻', '谷歌', 'Nano Banana', 'Mixboard', '通义万相', '可灵', '秘塔AI', 'Suno', 'AR游戏', '机器人技术', 'Sam Altman'],
      cover: 'https://wp-cdn.4ce.cn/v2/8u71qCz.png',
      content: '本周AI领域重磅更新：谷歌发布首款Nano Banana官方应用Mixboard开启AI画板新时代，阿里通义万相Wan2.5实现音画同步视频生成，快手可灵2.5 Turbo成本暴降30%效果飞跃，秘塔AI推出Agentic Search边想边搜边做，Suno V5模型达到录音室级音质。',
      recommend: true,
      top: true,
      link: '/article/daily-ai-news-september-25-2025'
    },
    {
      id: 'info-026',
      title: '阿里云栖大会模型七连发：通义千问3-Max超越GPT-5，全模态AI生态全面升级',
      date: '2025-09-25',
      categories: 'AI技术',
      tags: ['阿里', '云栖大会', '通义千问', 'Qwen3-Max', 'Qwen3-VL', 'Qwen3-Omni', '大模型', '开源', '多模态', 'AGI'],
      cover: 'https://wp-cdn.4ce.cn/v2/8u71qCz.png',
      content: '阿里云栖大会重磅发布七款新模型，通义千问Qwen3-Max性能跻身全球第三超越GPT-5，Qwen3-Next架构创新效率提升10倍，Qwen3-VL视觉理解达到SOTA水平，Qwen3-Omni全模态开源填补空白，构建从0.5B到480B全尺寸AI生态。',
      recommend: true,
      top: true,
      link: '/article/alibaba-yunqi-conference-model-releases-2025'
    }
  ]
}
